### PR TITLE
Resolve worktree .git files to repository .git directory

### PR DESCRIPTION
**Pull request by jkylling**
### Context
Fix https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/639
I have not tested this change end to end.

### Contributor Checklist
- [x] Added relevant integration or unit tests to verify the changes
- [x] Update the Readme or any other documentation (including relevant Javadoc)
- [x] Ensured that tests pass locally: `mvn clean package`
- [x] Ensured that the code meets the current `checkstyle` coding style definition: `mvn clean verify -Pcheckstyle -Dmaven.test.skip=true -B`

### CODE REVIEW

**Comment by TheSnoozer** [comment]
Do you have better suggestions @xkrogen?

**Comment by xkrogen** [comment]
I took a quick read through the [Details section for git-worktree](https://git-scm.com/docs/git-worktree#_details) and the worktree-related stuff in [gitrepository-layout](https://git-scm.com/docs/gitrepository-layout). It seems like this should work if we assume the `GIT_DIR` and `GIT_COMMON_DIR` environment variables aren't set. Not sure if we should consider them here?

There is also the potential situation where `.git` is a text file containing a `gitpath` spec, instead of a directory. Also not sure if `git-commit-id` handles this situation generally; if so, should we also handle that here?

**Comment by jkylling** [comment]
@TheSnoozer I've gone through the contributor checklist and fixed the check style violations. Do you think we should merge this?

**Comment by TheSnoozer** [comment]
Thanks again for your contribution! Merged now.

**Comment by xkrogen** [comment]
Hey @TheSnoozer just curious when you expect this to go into a release? I'm not familiar with the release lifecycle of this project, just wondering when I'll be able to adopt it downstream.

Big thanks to both of you btw :)

**Comment by TheSnoozer** [comment]
The release cycle is to wait until someone mentions they want a release ;-)

Will do that as soon as I have time (sorry this project is still only my free time) :-)

**Comment by TheSnoozer** [comment]
Released now as 7.0.0 via https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/623.

**Comment by xkrogen** [comment]
Heh awesome ... Thanks so much @TheSnoozer !

**Pull request merged**
